version: "3.8"
services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - "/code/node_modules"
      - "./:/code"
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0